### PR TITLE
Templatize confd toml and tmpl files

### PR DESCRIPTION
**Pull request by limed**
This commit attempts to change the way this module, it will now templatize the confd tmpl and toml files. This will allow us to have more granular control on the node levels to grant users for specific ldap groups.

Doing this will move all the confd files from nubis-base to here

### CODE REVIEW

**Comment by limed** [comment]
Fixes issue #6

**Comment by gozer** [comment]
Since this is a fairly big chunk of refactoring, I'd like to give this a test run before I merge it in.

Any suggestions as to how I can easily do that? I am a bit at a loss...

Should I be able to rebuild nubis-base using a diff something like this:

```diff
diff --git a/nubis/Puppetfile b/nubis/Puppetfile
index 97fce9e..d30fe06 100644
--- a/nubis/Puppetfile
+++ b/nubis/Puppetfile
@@ -73,8 +73,8 @@ mod 'nubis/mig',
     :ref => 'v1.0.1-2'

 mod 'nubis/nubis_users',
-    :git => 'https://github.com/nubisproject/nubis-puppet-nubis_users',
-    :ref => 'v1.1.0'
+    :git => 'https://github.com/limed/nubis-puppet-nubis_users',
+    :ref => '1341db41e12d8f3381b49d6ef1f8b80c322f3576'

 # This developer doesn't tag his releases on github
 # https://github.com/maxchk/puppet-varnish/pull/57
```

**Comment by limed** [comment]
> Should I be able to rebuild nubis-base using a diff something like this:

I would do that, and then remove all the stuff in https://github.com/nubisproject/nubis-base/blob/master/nubis/puppet/nubis_users.pp and just place in 

```
include nubis_users::setup
```

**Comment by gozer** [comment]
Looking good!

Only annoying little nit is that if there is no data in consul for what it's looking for, the puppet runs fails, but since there is no data, it's not exactly a show stopper.

I'd say, let's just file an issue to fix it later.
```bash
2016-10-27T19:01:55Z ip-10-164-19-74 confd[4242]: DEBUG Running puppet apply --hiera_config /etc/puppet/hiera.yaml --modulepath /etc/puppet/modules/ -e 'include nubis_users'
2016-10-27T19:01:57Z ip-10-164-19-74 confd[4242]: ERROR "\x1b[1;31mError: Could not run: Hiera type mismatch: expected Hash and got NilClass\x1b[0m\n"
```

**Pull request merged**
